//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace NFSENacionalClient.Classes
{

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
    public class SignatureType
    {

        /// <remarks/>
        public SignedInfoType SignedInfo;

        /// <remarks/>
        public SignatureValueType SignatureValue;

        /// <remarks/>
        public KeyInfoType KeyInfo;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class SignedInfoType
    {

        /// <remarks/>
        public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod;

        /// <remarks/>
        public SignedInfoTypeSignatureMethod SignatureMethod;

        /// <remarks/>
        public ReferenceType Reference;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id;
    }


    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class SignedInfoTypeCanonicalizationMethod
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string Algorithm;

        public SignedInfoTypeCanonicalizationMethod()
        {
            this.Algorithm = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
        }
    }

    /// <remarks/>

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class X509DataType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] X509Certificate;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class KeyInfoType
    {

        /// <remarks/>
        public X509DataType X509Data;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class SignatureValueType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class TransformType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public string[] XPath;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TTransformURI Algorithm;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public enum TTransformURI
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
        httpwwww3org200009xmldsigenvelopedsignature,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class ReferenceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
        public TransformType[] Transforms;

        /// <remarks/>
        public ReferenceTypeDigestMethod DigestMethod;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] DigestValue;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string URI;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string Type;
    }


    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class ReferenceTypeDigestMethod
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string Algorithm;

        public ReferenceTypeDigestMethod()
        {
            this.Algorithm = "http://www.w3.org/2000/09/xmldsig#sha1";
        }
    }


    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public class SignedInfoTypeSignatureMethod
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string Algorithm;

        public SignedInfoTypeSignatureMethod()
        {
            this.Algorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
        }
    }


    [System.Xml.Serialization.XmlRootAttribute("DPS", Namespace = "http://www.sped.fazenda.gov.br/nfse", IsNullable = false)]
    public class TCDPS
    {

        /// <remarks/>
        public TCInfDPS infDPS;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string versao;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfDPS
    {

        /// <remarks/>
        public TSTipoAmbiente tpAmb;

        /// <remarks/>
        public string dhEmi;

        /// <remarks/>
        public string verAplic;

        /// <remarks/>
        public string serie;

        /// <remarks/>
        public string nDPS;

        /// <remarks/>
        public string dCompet;

        /// <remarks/>
        public TSEmitenteDPS tpEmit;

        /// <remarks/>
        public TCSubstituicao subst;

        /// <remarks/>
        public TCInfoAtor prest;

        /// <remarks/>
        public TCInfoAtor toma;

        /// <remarks/>
        public TCInfoAtor interm;

        /// <remarks/>
        public TCServPrest serv;

        /// <remarks/>
        public TCInfoTributacao trib;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoAmbiente
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Producao,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Homologacao,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSEmitenteDPS
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Prestador,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Tomador,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Intermediario,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCSubstituicao
    {

        /// <remarks/>
        public string chSubstda;

        /// <remarks/>
        public TSCodJustSubst cMotivo;

        /// <remarks/>
        public string xMotivo;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSCodJustSubst
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfoAtor
    {
        public string CPF;
        public string CNPJ;
        public string NIF;

        /// <remarks/>
        public string IM;

        /// <remarks/>
        public string xNome;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enderExt", typeof(TCEnderExt))]
        [System.Xml.Serialization.XmlElementAttribute("enderNac", typeof(TCEnderNac))]
        public object Endereco;

        /// <remarks/>
        public string fone;

        /// <remarks/>
        public string email;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        CNPJ,

        /// <remarks/>
        CPF,

        /// <remarks/>
        NIF,
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCEnderExt
    {

        /// <remarks/>
        public string cPais;

        /// <remarks/>
        public string xEnderExt;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCEnderNac
    {

        /// <remarks/>
        public string xLgr;

        /// <remarks/>
        public string nro;

        /// <remarks/>
        public string xCpl;

        /// <remarks/>
        public string xBairro;

        /// <remarks/>
        public string cMun;

        /// <remarks/>
        public TSUF UF;

        /// <remarks/>
        public string CEP;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSUF
    {

        /// <remarks/>
        AC,

        /// <remarks/>
        AL,

        /// <remarks/>
        AM,

        /// <remarks/>
        AP,

        /// <remarks/>
        BA,

        /// <remarks/>
        CE,

        /// <remarks/>
        DF,

        /// <remarks/>
        ES,

        /// <remarks/>
        GO,

        /// <remarks/>
        MA,

        /// <remarks/>
        MG,

        /// <remarks/>
        MS,

        /// <remarks/>
        MT,

        /// <remarks/>
        PA,

        /// <remarks/>
        PB,

        /// <remarks/>
        PE,

        /// <remarks/>
        PI,

        /// <remarks/>
        PR,

        /// <remarks/>
        RJ,

        /// <remarks/>
        RN,

        /// <remarks/>
        RO,

        /// <remarks/>
        RR,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SE,

        /// <remarks/>
        SP,

        /// <remarks/>
        TO,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCServPrest
    {

        /// <remarks/>
        public string cMunPrestacao;

        /// <remarks/>
        public string cPaisPrestacao;

        /// <remarks/>
        public string cTribNac;

        /// <remarks/>
        public string cTribMun;

        /// <remarks/>
        public string xDescServ;

        /// <remarks/>
        public string cNBS;

        /// <remarks/>
        public string vReceb;

        /// <remarks/>
        public string vServ;

        /// <remarks/>
        public string vDescIncond;

        /// <remarks/>
        public string vDescCond;

        /// <remarks/>
        public TCComExterior comExt;

        /// <remarks/>
        public TCPedagio pedagio;

        /// <remarks/>
        public TCAtvEvento atvEvento;

        /// <remarks/>
        public TCInfoObra obra;

        /// <remarks/>
        public string idDocTec;

        /// <remarks/>
        public string docRef;

        /// <remarks/>
        public string xInfComp;

        /// <remarks/>
        public TCInfoDedRed dedRed;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCComExterior
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtIniPrest;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtFimPrest;

        /// <remarks/>
        public TSModPrestComExt mdPrestacao;

        /// <remarks/>
        public string tpMoeda;

        /// <remarks/>
        public string vServMoeda;

        /// <remarks/>
        public TSEnquadRVS enquadRVS;

        /// <remarks/>
        public TSEnquadRPC enquadRPC;

        /// <remarks/>
        public TSMovTempBens movTempBens;

        /// <remarks/>
        public string nDI;

        /// <remarks/>
        public string nRE;

        /// <remarks/>
        public string mdic;
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSModPrestComExt
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSEnquadRVS
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSEnquadRPC
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSMovTempBens
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCPedagio
    {

        /// <remarks/>
        public string placa;

        /// <remarks/>
        public string nEixos;

        /// <remarks/>
        public string sentido;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCAtvEvento
    {

        /// <remarks/>
        public string desc;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtIni;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtFim;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ender", typeof(TCEnderNac))]
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(string))]
        public object Item;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfoObra
    {

        /// <remarks/>
        public string cObra;

        /// <remarks/>
        public string inscImobFisc;

        /// <remarks/>
        public TCEnderNac ender;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfoDedRed
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documento", typeof(TCDocDedRed))]
        [System.Xml.Serialization.XmlElementAttribute("pDR", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vDR", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCDocDedRed
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NFNFS", typeof(TCDocNFNFS))]
        [System.Xml.Serialization.XmlElementAttribute("chNFSe", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("chNFe", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("outDoc", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("outDocFisc", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("outNotaeMun", typeof(TCDocOutNFSe))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName;

        /// <remarks/>
        public TSIdeDedRed tipo;

        /// <remarks/>
        public string xDescOut;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtEmiDoc;

        /// <remarks/>
        public string vDedutivelRedutivel;

        /// <remarks/>
        public string vDeducaoReducao;

        /// <remarks/>
        public TCInfoAtor forne;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCDocNFNFS
    {

        /// <remarks/>
        public string nNFS;

        /// <remarks/>
        public string modNFS;

        /// <remarks/>
        public string serieNFS;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCDocOutNFSe
    {

        /// <remarks/>
        public string cMunNota;

        /// <remarks/>
        public string nNota;

        /// <remarks/>
        public string cvNota;
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        NFNFS,

        /// <remarks/>
        chNFSe,

        /// <remarks/>
        chNFe,

        /// <remarks/>
        outDoc,

        /// <remarks/>
        outDocFisc,

        /// <remarks/>
        outNotaeMun,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSIdeDedRed
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        documento,

        /// <remarks/>
        pDR,

        /// <remarks/>
        vDR,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfoTributacao
    {

        /// <remarks/>
        public TSOpSimpNac opSimpNac;

        /// <remarks/>
        public TSOpSNLimUltrap opLimMEI;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opLimMEISpecified;

        /// <remarks/>
        public TSOpSNLimUltrap opLimSimpNac;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opLimSimpNacSpecified;

        /// <remarks/>
        public TCTribISSQN issqn;

        /// <remarks/>
        public TCTribOutros outros;

        /// <remarks/>
        public TCTribTotal totTrib;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSOpSimpNac
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSOpSNLimUltrap
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCTribISSQN
    {

        /// <remarks/>
        public TSRegEspTrib regEspTrib;

        /// <remarks/>
        public TSExigibISSQN exigISSQN;

        /// <remarks/>
        public string nBMIsenc;

        /// <remarks/>
        public string vInfoBM;

        /// <remarks/>
        public string nProcesso;

        /// <remarks/>
        public TSTipoImunidadeISSQN tpImunidade;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tpImunidadeSpecified;

        /// <remarks/>
        public string pAliq;

        /// <remarks/>
        public TSTipoRetISSQN tpRetISSQN;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSRegEspTrib
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSExigibISSQN
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Tipo1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Tipo2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Tipo3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Tipo4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Tipo5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Tipo6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Tipo7,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoImunidadeISSQN
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoRetISSQN
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCTribOutros
    {

        /// <remarks/>
        public TSTipoCST CST;

        /// <remarks/>
        public string vBCPisCofins;

        /// <remarks/>
        public string pAliqPis;

        /// <remarks/>
        public string pAliqCofins;

        /// <remarks/>
        public string vPis;

        /// <remarks/>
        public string vCofins;

        /// <remarks/>
        public TSTipoRetPISCofins tpRetPisConfins;

        /// <remarks/>
        public string vRetCP;

        /// <remarks/>
        public string vRetIRRF;

        /// <remarks/>
        public string vRetCSLL;
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoCST
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoRetPISCofins
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCTribTotal
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indTotTrib", typeof(TSTipoIndTotTrib))]
        [System.Xml.Serialization.XmlElementAttribute("pTotTrib", typeof(TCTribTotalPercent))]
        [System.Xml.Serialization.XmlElementAttribute("pTotTribSN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("vTotTrib", typeof(TCTribTotalMonet))]
        public object Item;
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoIndTotTrib
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }


    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCTribTotalPercent
    {

        /// <remarks/>
        public string pTotTribFed;

        /// <remarks/>
        public string pTotTribEst;

        /// <remarks/>
        public string pTotTribMun;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCTribTotalMonet
    {

        /// <remarks/>
        public string vTotTribFed;

        /// <remarks/>
        public string vTotTribEst;

        /// <remarks/>
        public string vTotTribMun;
    }
}