//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace NFSENacionalClient.Classes
{
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    [System.Xml.Serialization.XmlRootAttribute("NFSe", Namespace = "http://www.sped.fazenda.gov.br/nfse", IsNullable = false)]
    public class TCNFSe
    {

        /// <remarks/>
        public TCInfNFSe infNFSe;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string versao;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCInfNFSe
    {

        /// <remarks/>
        public string cMunEmi;

        /// <remarks/>
        public string xMunEmi;

        /// <remarks/>
        public string cMunIncid;

        /// <remarks/>
        public string xMunIncid;

        /// <remarks/>
        public string nNFSe;

        /// <remarks/>
        public string xTribNac;

        /// <remarks/>
        public string xTribMun;

        /// <remarks/>
        public string xNBS;

        /// <remarks/>
        public string verAplic;

        /// <remarks/>
        public TSAmbienteGerador ambGer;

        /// <remarks/>
        public TSTipoEmissao tpEmis;

        /// <remarks/>
        public TSProcEmissao procEmi;

        /// <remarks/>
        public string cStat;

        /// <remarks/>
        public string dhProc;

        /// <remarks/>
        public TCEmitente emit;

        /// <remarks/>
        public TCValoresNFSe valores;

        /// <remarks/>
        public TCDPS DPS;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id;
    }


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSAmbienteGerador
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSTipoEmissao
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public enum TSProcEmissao
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCEmitente
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName;

        /// <remarks/>
        public string xNome;

        /// <remarks/>
        public string xFant;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enderExt", typeof(TCEnderExt))]
        [System.Xml.Serialization.XmlElementAttribute("enderNac", typeof(TCEnderNac))]
        public object Item1;

        /// <remarks/>
        public string fone;

        /// <remarks/>
        public string email;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse")]
    public class TCValoresNFSe
    {

        /// <remarks/>
        public string vCalcDR;

        /// <remarks/>
        public string pRedBCBM;

        /// <remarks/>
        public string vCalcBM;

        /// <remarks/>
        public string vBC;

        /// <remarks/>
        public string pAliqAplic;

        /// <remarks/>
        public string vISSQN;

        /// <remarks/>
        public string vTotalRet;

        /// <remarks/>
        public string vLiq;

        /// <remarks/>
        public string xOutInf;
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sped.fazenda.gov.br/nfse", IncludeInSchema = false)]
    public enum ItemChoiceType2
    {

        /// <remarks/>
        NFNFS,

        /// <remarks/>
        chNFSe,

        /// <remarks/>
        chNFe,

        /// <remarks/>
        outDoc,

        /// <remarks/>
        outDocFisc,

        /// <remarks/>
        outNotaeMun,
    }
}